selenium template init
jdi-templates/jdn-template-selenium pull request #1
Opened 2024-01-03 09:28 UTC by spbqaru

selenium template init

2024-01-06 02:17 UTC, pnatashap requested changes

2024-01-06 02:17 UTC, pnatashap commented on pom.xml
> +<!--        <allure.testng>2.23.0</allure.testng>-->
коменты и ненужные параметры надо убрать

2024-01-09 12:48 UTC, spbqaru commented on pom.xml
> +<!--        <allure.testng>2.23.0</allure.testng>-->
обновил

2024-01-10 18:43 UTC, pnatashap requested changes
и все еще нет action, который бы проверял, что шаблон живой

2024-01-10 18:43 UTC, pnatashap commented on src/main/java/utilities/ConfigReader.java
> +        try (InputStream input = new FileInputStream("./src/test/resources/" + propertyFileName)) {
давай не будем канонозировать эту чрезвычайно плохую практику чтения из исходников

2024-01-16 12:44 UTC, spbqaru commented on src/main/java/utilities/ConfigReader.java
> +        try (InputStream input = new FileInputStream("./src/test/resources/" + propertyFileName)) {
заменил на AppConfig.java

2024-01-18 14:55 UTC, pnatashap requested changes

2024-01-18 14:55 UTC, pnatashap commented on .github/workflows/build.yml
> +      - name: Start Selenoid
а зачем нам тут selenoid?

2024-01-18 14:55 UTC, pnatashap commented on .github/workflows/build.yml
> +      - name: Deploy Allure report to Github Pages
плохо работает, если тесты в параллели гонять

2024-01-18 21:00 UTC, spbqaru commented on .github/workflows/build.yml
> +      - name: Start Selenoid
убрал

2024-01-18 21:00 UTC, spbqaru commented on .github/workflows/build.yml
> +      - name: Deploy Allure report to Github Pages
убрал

2024-01-22 13:11 UTC, merged